### ISSUE TITLE
how to download beatmap ? ( android )

### ISSUE THREAD

**Issue by View-my-Git-Lab-krafi** [ojh050118/Circle#155]
how to download beatmap ? ( android ) 

also i want to make release for Linux

**Comment by ojh050118** [comment]
First of all, thank you for your interest in Circle.

This client is currently unable to download beatmaps from online.
Instead, you need to convert the adofai level to a circle beatmap and import the beatmap using "Import beatmap" in the settings.

Since beatmap conversion is not yet available in the client (I will be implementing this feature after November), you'll have to use an external program for the time being. You can convert beatmaps using [ojh050118/Adofai-to-Circle](https://github.com/ojh050118/Adofai-to-Circle). If you need any help please feel free to mention me.


> also i want to make release for Linux

If you want to release the client for Linux, you have to compile it in a Linux environment.
